//Log in
export const LOGIN_SAGA = 'LOGIN_SAGA';

//Sign up
export const SIGN_UP_SAGA = 'SIGN_UP_SAGA';
export const DISPLAY_SIGN_UP_MODAL = 'DISPLAY_SIGN_UP_MODAL';
export const HIDE_SIGN_UP_MODAL = 'HIDE_SIGN_UP_MODAL';

//User profile
export const GET_PROFILE_DETAIL_BY_ID_SAGA = 'GET_PROFILE_DETAIL_BY_ID_SAGA';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const UPDATE_PROFILE_SAGA = 'UPDATE_PROFILE_SAGA';

//City
export const GET_CITY_LIST_SAGA = 'GET_CITY_LIST_SAGA';
export const GET_CITY_LIST = 'GET_CITY_LIST';

//School
export const GET_SCHOOL_LIST_SAGA = 'GET_SCHOOL_LIST_SAGA';
export const GET_SCHOOL_LIST = 'GET_SCHOOL_LIST';

//College
export const GET_COLLEGE_LIST_SAGA = 'GET_COLLEGE_LIST_SAGA';
export const GET_COLLEGE_LIST = 'GET_COLLEGE_LIST';

//Workplace
export const GET_WORKPLACE_LIST_SAGA = 'GET_WORKPLACE_LIST_SAGA';
export const GET_WORKPLACE_LIST = 'GET_WORKPLACE_LIST';

//Post
export const DISPLAY_CREATE_POST_MODAL = 'DISPLAY_CREATE_POST_MODAL';
export const HIDE_CREATE_POST_MODAL = 'HIDE_CREATE_POST_MODAL';

//Menu
export const SET_HOME_MENU_ID_ACTIVE = 'SET_HOME_MENU_ID_ACTIVE';
export const SET_FRIENDS_MENU_ID_ACTIVE = 'SET_FRIENDS_MENU_ID_ACTIVE';

//Photo
export const DISPLAY_VIEW_PHOTO_MODAL = 'DISPLAY_VIEW_PHOTO_MODAL';
export const HIDE_VIEW_PHOTO_MODAL = 'HIDE_VIEW_PHOTO_MODAL';
export const DISPLAY_UPLOAD_IMAGE_MODAL = 'DISPLAY_UPLOAD_IMAGE_MODAL';
export const HIDE_UPLOAD_IMAGE_MODAL = 'HIDE_UPLOAD_IMAGE_MODAL';